# Generated by Django 4.0.4 on 2022-05-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Coût'),
        ),
    ]
