# Generated by Django 4.0.4 on 2022-05-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='external_stock',
        ),
    ]
