# Generated by Django 4.0 on 2022-03-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockManager', '0002_auto_20211103_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
