# Generated by Django 4.0.4 on 2022-05-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='user',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='user',
        ),
        migrations.DeleteModel(
            name='HolidayRequest',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
